#!/bin/bash

APP_PATH=/var/www/foofoberry/api
GIT_DIR=/var/repo/foofoberry/api.git

[[ -s "/usr/local/rvm/bin/rvm" ]] && . "/usr/local/rvm/bin/rvm"

git --work-tree=${APP_PATH} --git-dir=${GIT_DIR} checkout -f
echo "==========  CODE DEPLOYED =========="

cd ${APP_PATH}
/usr/local/rvm/gems/ruby-2.0.0-p353@global/bin/bundle install --deployment
echo "==========  BUNDLED  =========="

#/usr/local/rvm/gems/ruby-2.0.0-p353/bin/rake db:migrate
#echo "MIGRATED"
